version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quest_service
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  quest-service:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: